# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Egor Shestopalov
tagline:          'Blog'
description:      'Personal blog'
url:              https://egshes.github.io/
baseurl:          /

author:
  name:           'Egor Shestopalov'
  url:            no

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/EgShes

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
